# General configuration
replicaCount: 1

# Application-specific settings
app:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/ardhra-977805/test-registry/nodejs-mongo-app_nodejs-app
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: registrykey  
  service:
    type: LoadBalancer
    port: 3000
  resources: {}  # Set specific CPU/Memory limits if requiredd

# MongoDB-specific settings
mongo:
   replicaCount: 1
   image:
     repository: mongo
     tag: 6.0.20-rc3-jammy #6.0.20
     port: 27017
   resources: {}  # Set specific CPU/Memory limits if required
