# General configuration
replicaCount: 1

# Application-specific settings
app:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/ardhra-977805/test-registry/nodejs-mongo-app_nodejs-app
    tag: 100
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: registrykey  
  service:
    type: LoadBalancer
    port: 3000
  resources: {}  # Set specific CPU/Memory limits if required

# MongoDB-specific settings
mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
    port: 27017
  resources: {}  # Set specific CPU/Memory limits if required
